### ISSUE TITLE
Conflicts with Extra Utilities 2 Diamond Spikes!

### ISSUE THREAD

**Issue by shufunk** [LaureeGrd/PPAPmod#3]
Here is the link to the crash log -- https://smallpaste.in/view/589fc199a46da1740c8b4569

I was testing out my modpack to get it ready for release. One mod in my modpack requires a lot of necrotic bones which is a drop from Wither Skeletons. The actual item itself is from Tinkers Construct but seems to be a shared ID for another mods that requires it.

TLDR:

I made an auto spawner with diamond spikes to kill the wither skeletons for me and get the drops i need since iron spikes don't do the job. It seems that when the Diamond Spike kills the Wither Skeleton it looks for possible drops that is meant for player kills and it sees has the PPAP disc and PPAP extended disk as possible drops but realizes the diamond spike is not a PPAP sword therefore it refuses to drop the items and crashes the game instead of allowing the mod to choose other items that are valid player drops.

This is resolved by removing the PPAP mod from the pack and the Diamond Spikes do not crash the game when a Wither Skeleton dies from it. I will be shareing this report to both mod makers since i am unable to determine which mod is bugged.

**Comment by LaureeGrd** [comment]
As I can assume by reading here https://ftbwiki.org/Diamond_Spike that "mobs killed by the Diamond Spike will return experience as if killed by the player", the block is probably using a DamageSource of EntityPlayer. So when I check if the mob was killed by a player, it continues with the code until I try to get the item in hand of that non-existant player. I will try to make the mods compatible :)

**Comment by shufunk** [comment]
I forgot i can turn off the ability to have it when a player uses the PPAP sword and mobs drop the discs. I turned on the feature to allow you to obtain a disk from using one sword in the crafting grid to obtain a disc. When i did that the Wither Skeletons die with the diamond spikes with no crash. That is the good news but this still needs to be fixed

**Comment by LaureeGrd** [comment]
Yes. I'm totally aware of it. I'll close this issue when fixed :)
